### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab/) and meets the following criteria:

- [x] The files from your last project are copied and pasted into the directory for this project
- [x] Your code returns no errors (warnings are OK) when pasted into the [W3C Validator](https://validator.w3.org/#validate_by_input) (this will also be expected for all future projects)
- [x] Consistent spacing and indentation are used on every line (this will also be expected for all future projects)
- [x] `skeleton.css` is used to improve the design of the page

**Comment by egillespie** [comment]
@kisyular Do you mind re-indenting your `index.html` file? Typically the `html` tag doesn't have any spaces before it and all other tags are indented inside it. We suggest using 2 spaces for indents as well. The lesson describes how to set this in Atom.

One other thing: it looks like there's a newline before the `"` at the end of your `link` element. You probably didn't intend to do that.

After you've made these changes, please comment back here and I'll take another look.

Thanks!

**Comment by kisyular** [comment]
@egillespie I have re-indented the index.html

**Comment by egillespie** [comment]
@kisyular Thanks! Looks much better now. For future projects, you may want to stick to 2-space indenting. We'll probably become more picky about this over time because you'll have more complicated content and the extra spaces will take up unnecessary room.

For now, :shipit:

**Comment by kisyular** [comment]
@egillespie Does 2-Space Indenting means 2 Tabs. That is how I set it to. I could not find on setting where to set 2-space indenting
![screen shot 2017-01-17 at 17 52 54](https://cloud.githubusercontent.com/assets/15636554/22043492/d109d642-dcdd-11e6-9844-6dc2a825e362.png)

These are my setting

**Comment by egillespie** [comment]
@kisyular Yep, you got it! Tab Length: 2 is what I was going for.
